### ISSUE TITLE
Kubic Doesn't install in VMWare

### ISSUE THREAD

**Issue by tgeek77** [kubic-project/e2e-tests#46]
![kubic-vmware](https://cloud.githubusercontent.com/assets/10347457/26541707/1e4d04a2-4457-11e7-85b2-a5410e3db461.png)

[y2log-18OHsh.tar.xz.zip](https://github.com/kubic-project/e2e-tests/files/1035219/y2log-18OHsh.tar.xz.zip)

VM Config:
ESXi 6.0U1
RAM: 2G
HDD: 60G

Also, there's no Bugzilla section for Kubic or I would open a bug the normal way.

**Comment by PI-Victor** [comment]
@tgeek77 yes, that's because internally it's called CaaSP. We're working on improving that. :)
i've opened a bug for your issue: https://bugzilla.suse.com/show_bug.cgi?id=1041458

**Comment by tgeek77** [comment]
Hi Victor, I'm actually a SUSE Employee (jevans) and I'm also working with CaaSP. I don't see this issue with the official CaaSP Beta 3 ISO, only with the latest Kubic ISO. I added myself to the Bugzilla bug and I'll update it also.

**Comment by PI-Victor** [comment]
ah, that's what you meant by `kubic`. i'm already confused of all the naming around this. i'll update the bug, but not sure either if caasp is a valid product for bugzilla. will find out and try to reassign it.

**Comment by PI-Victor** [comment]
closing this in favor of https://github.com/kubic-project/community/issues/4 the discussion can be continued there.
